-- FUNDAMENTALS: overview
-- Generated from ACTUAL API response investigation
-- Total fields in response: 55

CREATE TABLE overview (
    id BIGSERIAL PRIMARY KEY,
    symbol VARCHAR(10) PRIMARY KEY,
    assettype TEXT,
    name TEXT,
    description TEXT,
    cik TEXT,
    exchange TEXT,
    currency TEXT,
    country TEXT,
    sector TEXT,
    industry TEXT,
    address TEXT,
    officialsite TEXT,
    fiscalyearend TEXT,
    latestquarter TEXT,
    marketcapitalization TEXT,
    ebitda TEXT,
    peratio TEXT,
    pegratio TEXT,
    bookvalue TEXT,
    dividendpershare TEXT,
    dividendyield TEXT,
    eps TEXT,
    revenuepersharettm TEXT,
    profitmargin TEXT,
    operatingmarginttm TEXT,
    returnonassetsttm TEXT,
    returnonequityttm TEXT,
    revenuettm TEXT,
    grossprofitttm TEXT,
    dilutedepsttm TEXT,
    quarterlyearningsgrowthyoy TEXT,
    quarterlyrevenuegrowthyoy TEXT,
    analysttargetprice TEXT,
    analystratingstrongbuy TEXT,
    analystratingbuy TEXT,
    analystratinghold TEXT,
    analystratingsell TEXT,
    analystratingstrongsell TEXT,
    trailingpe TEXT,
    forwardpe TEXT,
    pricetosalesratiottm TEXT,
    pricetobookratio TEXT,
    evtorevenue TEXT,
    evtoebitda TEXT,
    beta TEXT,
    52weekhigh TEXT,
    52weeklow TEXT,
    50daymovingaverage TEXT,
    200daymovingaverage TEXT,
    sharesoutstanding TEXT,
    sharesfloat TEXT,
    percentinsiders TEXT,
    percentinstitutions TEXT,
    dividenddate TEXT,
    exdividenddate TEXT    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_overview_symbol ON overview(symbol) WHERE symbol IS NOT NULL;
CREATE INDEX idx_overview_date ON overview(date) WHERE date IS NOT NULL;
