-- Fundamental Data: overview
CREATE TABLE overview (
    symbol VARCHAR(10) PRIMARY KEY,
    assettype VARCHAR(50),
    name VARCHAR(10),
    description TEXT,
    cik NUMERIC,
    exchange VARCHAR(10),
    currency VARCHAR(10),
    country VARCHAR(10),
    sector VARCHAR(10),
    industry VARCHAR(50),
    address VARCHAR(50),
    officialsite VARCHAR(50),
    fiscalyearend VARCHAR(10),
    latestquarter DATE,
    marketcapitalization NUMERIC,
    ebitda NUMERIC,
    peratio NUMERIC,
    pegratio NUMERIC,
    bookvalue NUMERIC,
    dividendpershare NUMERIC,
    dividendyield NUMERIC,
    eps NUMERIC,
    revenuepersharettm NUMERIC,
    profitmargin NUMERIC,
    operatingmarginttm NUMERIC,
    returnonassetsttm NUMERIC,
    returnonequityttm NUMERIC,
    revenuettm NUMERIC,
    grossprofitttm NUMERIC,
    dilutedepsttm NUMERIC,
    quarterlyearningsgrowthyoy NUMERIC,
    quarterlyrevenuegrowthyoy NUMERIC,
    analysttargetprice NUMERIC,
    analystratingstrongbuy NUMERIC,
    analystratingbuy NUMERIC,
    analystratinghold NUMERIC,
    analystratingsell NUMERIC,
    analystratingstrongsell NUMERIC,
    trailingpe NUMERIC,
    forwardpe NUMERIC,
    pricetosalesratiottm NUMERIC,
    pricetobookratio NUMERIC,
    evtorevenue NUMERIC,
    evtoebitda NUMERIC,
    beta NUMERIC,
    field_52weekhigh NUMERIC,
    field_52weeklow NUMERIC,
    field_50daymovingaverage NUMERIC,
    field_200daymovingaverage NUMERIC,
    sharesoutstanding NUMERIC,
    sharesfloat NUMERIC,
    percentinsiders NUMERIC,
    percentinstitutions NUMERIC,
    dividenddate DATE,
    exdividenddate DATE,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_{table_name}_symbol ON {table_name}(symbol);
