# System configuration
system:
  name: "AlphaTrader Pro"
  version: "1.0.0"
  environment: "development"

# Market configuration
market:
  check_staleness_after_hours: false
  extended_hours: false

# Redis configuration
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: null
  decode_responses: true
  max_connections: 50
  socket_keepalive: true

# IBKR configuration
ibkr:
  host: "127.0.0.1"
  port: 7497  # 7497 for paper, 7496 for live
  client_id: 1
  timeout: 10
  readonly: false
  
  # Exchange-specific L2 configuration
  level2_exchanges:
    SPY: ["ARCA", "BATS", "IEX"]
    QQQ: ["ISLAND", "ARCA", "BATS"]
    IWM: ["ARCA", "BATS"]
  
  smart_depth: false  # Never use SMART aggregation
  l2_num_rows: 10
  max_reconnect_attempts: 10
  reconnect_delay_base: 2

# Alpha Vantage configuration
alpha_vantage:
  api_key: "${ALPHA_VANTAGE_API_KEY}"
  base_url: "https://www.alphavantage.co/query"
  calls_per_minute: 600
  safety_buffer: 10
  retry_attempts: 3
  retry_delay: 2
  options_update_interval: 10
  sentiment_update_interval: 300
  technicals_update_interval: 60

# Symbols configuration
symbols:
  level2: ["SPY", "QQQ", "IWM"]
  standard: ["AAPL", "TSLA", "NVDA", "AMD", "GOOGL", "META", "AMZN", "MSFT", "VXX"]

# Modules configuration
modules:
  data_ingestion:
    enabled: true
    data_freshness_threshold: 5
    
    # Single TTL source
    store_ttls:
      market_data: 60      # Keep quotes for 1 minute
      order_book: 60       # Keep order books for 1 minute  
      bars: 3600           # Keep bars for 1 hour (need 100+ for analytics)
      trades: 3600         # Keep trades for 1 hour (need 1000+ for VPIN)
      options_chain: 60    # Keep options for 1 minute
      greeks: 60          # Keep greeks for 1 minute
      sentiment: 300      # Keep sentiment for 5 minutes
      technicals: 300     # Keep technicals for 5 minutes
      metrics: 60         # Keep metrics for 1 minute
      monitoring: 60
      heartbeat: 15
  
  analytics:
    enabled: true
    cadence_hz: 2
    analytics_rth_only: false
  
  signals:
    enabled: false  # Day 5+
  
  execution:
    enabled: false  # Day 6+
  
  dashboard:
    enabled: false  # Day 7+
  
  social_media:
    enabled: false  # Day 7+

# Risk configuration (Day 6+)
risk:
  circuit_breakers:
    enabled: false
    max_daily_loss: 5000
    max_position_loss: 1000
    max_correlation: 0.7
    halt_on_disconnect: true

# Parameter discovery configuration (kept for reference)
parameter_discovery:
  enabled: true
  run_on_startup: true
  startup_delay: 60  
  interval_seconds: 900  
  schedule: "0 9 * * *"  
  ttl_seconds: 86400  
  data_staleness_threshold: 3600  
  
  vpin:
    min_bucket_size: 50
    max_bucket_size: 500
    num_clusters: 5
    min_trades_required: 1000
    default_bucket_size: 100
  
  temporal:
    max_lookback: 30
    min_bars_required: 100
    significance_threshold: 0.05
    default_lookback: 10
  
  market_makers:
    toxic_list: ["CDRG", "JANE", "VIRTU", "SUSG"]
    hft_size_threshold: 100
    institutional_size_threshold: 1000
    min_orders_required: 100
    toxicity_scores:
      toxic: 1.0
      hft: 0.7
      institutional: 0.2
      other: 0.3
  
  volatility:
    window_bars: 20
    low_percentile: 33
    high_percentile: 67
    bars_per_day: 4680
    trading_days_per_year: 252
    min_bars_for_regime: 500
    default_regime: "NORMAL"
  
  correlation:
    min_bars: 100
    calculation_window: 500
    forward_fill_limit: 5
    min_correlation_symbols: 3

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/alphatrader.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5
  console: true
  colorize: true

# Monitoring configuration
monitoring:
  health_check_interval: 1
  heartbeat_timeout: 10
  alert_email: null