# System configuration
system:
  name: "AlphaTrader Pro"
  version: "1.0.0"
  environment: "development"

# Market configuration
market:
  check_staleness_after_hours: false
  extended_hours: true

# Redis configuration
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: null
  decode_responses: true
  max_connections: 100  # Increased for high throughput
  socket_keepalive: true

# IBKR configuration
ibkr:
  host: "127.0.0.1"
  port: 7497  # 7497 for paper, 7496 for live
  client_id: 1
  timeout: 10
  readonly: false
  
  # Exchange-specific L2 configuration
  level2_exchanges:
    SPY: ["ARCA", "BATS", "IEX"]
    QQQ: ["ISLAND", "ARCA", "BATS"]
    IWM: ["ARCA", "BATS"]
  
  smart_depth: false  # Never use SMART aggregation
  l2_num_rows: 10
  max_reconnect_attempts: 10
  reconnect_delay_base: 2

# Alpha Vantage configuration
alpha_vantage:
  api_key: "${ALPHA_VANTAGE_API_KEY}"
  base_url: "https://www.alphavantage.co/query"
  calls_per_minute: 600
  safety_buffer: 10
  retry_attempts: 3
  retry_delay: 2
  failure_threshold: 3
  failure_backoff_seconds: 120
  failure_backoff_max: 900
  options_pubsub_channel: "events:options:chain"
  sentiment:
    skip_symbols: ["SPY", "QQQ", "IWM", "VXX"]
  options_update_interval: 10
  sentiment_update_interval: 300
  technicals_update_interval: 60

# Symbols configuration
symbols:
  level2: ["SPY", "QQQ", "IWM"]
  standard: ["AAPL", "TSLA", "NVDA", "AMD", "GOOGL", "META", "AMZN", "MSFT", "VXX"]

# Modules configuration
modules:
  data_ingestion:
    enabled: true
    data_freshness_threshold: 5
    
    # Single TTL source (balanced for analytics requirements)
    store_ttls:
      market_data: 60      # Keep quotes for 1 minute
      order_book: 60       # Keep order books for 1 minute  
      bars: 3600           # Keep bars for 1 hour (need 100+ for analytics)
      trades: 3600         # Keep trades for 1 hour (need 1000+ for VPIN)
      options_chain: 300    # Keep options for 1 minute
      greeks: 300           # Keep greeks for 1 minute
      sentiment: 300       # Keep sentiment for 5 minutes
      technicals: 300      # Keep technicals for 5 minutes
      metrics: 60          # Keep metrics for 1 minute
      monitoring: 60       # Keep monitoring for 1 minute
      heartbeat: 15        # Keep heartbeat for 15 seconds
  
  analytics:
    enabled: true
    cadence_hz: 2
    analytics_rth_only: false
    store_ttls:
      analytics: 60
      portfolio: 60
      sector: 120
      correlation: 900
      heartbeat: 15
    update_intervals:
      vpin: 5
      gex_dex: 30
      flow_toxicity: 60
      order_book: 1
      sweep_detection: 2
      portfolio: 15
      sectors: 30
      correlation: 300
    sector_map:
      SPY: INDEX
      QQQ: TECH
      IWM: SMALLCAP
      AAPL: TECH
      TSLA: AUTO
      NVDA: TECH
      AMD: SEMI
      GOOGL: TECH
      META: TECH
      AMZN: CONSUMER
      MSFT: TECH
      VXX: VOLATILITY
  
  signals:
    enabled: true
    dry_run: true
    publish_channel: "signals:out"

    # Guardrails (apply before any strategy logic)
    max_staleness_s: 60        # upstream inputs must be this fresh
    min_confidence: 0.60      # global floor; per-strategy may override
    min_refresh_s: 5          # min spacing between recalcs per symbol (increased from 2 to reduce churn)
    cooldown_s: 30            # block re-emitting same contract within window (now contract-scoped)
    ttl_seconds: 300          # TTL for emitted keys
    version: "D6.0.1"

    # Optional global blend (for future hybrid scorers)
    weights:
      vpin: 0.25
      toxicity: 0.20
      gex: 0.20
      dex: 0.10
      trend: 0.20
      vol: 0.05

    strategies:
      0dte:
        enabled: true
        symbols: ["SPY","QQQ","IWM"]
        time_window: { start: "09:45", end: "16:00" }  # Market hours only
        confidence_weights:
          vpin: 30
          obi: 25
          gamma_proximity: 30
          sweep: 15
        thresholds:
          min_confidence: 60
          vpin_min: 0.40
          obi_min: 0.30
          gamma_pin_distance: 0.005   # 0.5%

      1dte:
        enabled: true
        symbols: ["SPY","QQQ","IWM","VXX"]
        time_window: { start: "14:00", end: "16:00" }  # Afternoon session
        confidence_weights:
          volatility_regime: 20
          obi: 30
          gex: 25
          vpin: 25
        thresholds:
          min_confidence: 65

      14dte:
        enabled: true
        symbols: ["AAPL","TSLA","NVDA","AMD","GOOGL","META","AMZN","MSFT","PLTR"]
        time_window: { start: "09:30", end: "16:00" }  # Full market hours
        confidence_weights:
          unusual_options: 40
          sweep: 30
          hidden_orders: 20
          dex: 10
        thresholds:
          min_confidence: 70

      moc:
        enabled: true
        symbols: ["SPY","QQQ"]
        time_window: { start: "15:30", end: "16:00" }  # MOC window
        # Confidence components (sum to 100 possible)
        confidence_weights:
          imbalance_strength: 45     # size & ratio
          gamma_pull: 25             # towards nearest pin
          obi: 20                    # intraday book skew
          friday_factor: 10          # optional uplift (weekly flows)
        thresholds:
          min_confidence: 60
          min_imbalance_notional: 2.0e9      # $2B combined or symbol-appropriate
          min_imbalance_ratio: 0.60          # |Imbalance| / (Paired + |Imbalance|)
          max_spread_bps: 8                  # option NBBO spread ≤ 8 bps of spot
          min_option_oi: 2000                # open interest floor per leg
          max_contract_gamma_risk: 0.020     # approximate ΔGamma vs 0.5% move
        options:
          expiry: "0DTE"                     # same-day
          side: "trend"                      # with the imbalance direction
          target_delta: 0.25                 # ~25d
          alt_delta_if_pin: 0.15             # farther OTM if pin risk is high
          max_mid_slippage_bps: 4            # quoted vs mid control
          exit: "close"                      # conceptual; Day-6 = signals only

    distribution:
      tiers:
        premium: { delay_seconds: 0,   include_all_details: true }
        basic:   { delay_seconds: 60,  include_all_details: false }
        free:    { delay_seconds: 300, include_all_details: false }
  
  execution:
    enabled: true  # Day 6+
  
  dashboard:
    enabled: false  # Day 7+
  
  social_media:
    enabled: false  # Day 7+

# Risk Management configuration (Day 7)
risk_management:
  enabled: true
  max_daily_loss_pct: 2.0          # 2% of account value
  max_position_loss_pct: 1.0        # 1% max loss per position
  consecutive_loss_limit: 3         # Halt after 3 consecutive losses
  correlation_limit: 0.7            # Max portfolio correlation
  margin_buffer: 1.25               # 25% margin buffer required
  max_drawdown_pct: 10.0           # 10% max drawdown from HWM
  
  # Circuit breakers
  circuit_breakers:
    daily_loss: true
    consecutive_losses: true
    volatility_spike: true
    system_errors: true
    max_drawdown: true
  
  # VaR parameters
  var_confidence: 0.95              # 95% confidence level
  var_lookback_days: 30             # Days of history for VaR
  
  # Position limits
  max_positions: 5                  # Max concurrent positions
  max_per_symbol: 2                 # Max positions per symbol

# Legacy risk configuration (kept for backward compatibility)
risk:
  circuit_breakers:
    enabled: false
    max_daily_loss: 5000
    max_position_loss: 1000
    max_correlation: 0.7
    halt_on_disconnect: true

# Parameter discovery configuration (kept for reference)
parameter_discovery:
  enabled: true
  run_on_startup: true
  startup_delay: 60  
  interval_seconds: 900  
  schedule: "0 9 * * *"  
  ttl_seconds: 86400  
  data_staleness_threshold: 3600  
  
  vpin:
    min_bucket_size: 50
    max_bucket_size: 500
    num_clusters: 5
    min_trades_required: 1000
    default_bucket_size: 100
  
  temporal:
    max_lookback: 30
    min_bars_required: 100
    significance_threshold: 0.05
    default_lookback: 10
  
  market_makers:
    toxic_list: ["CDRG", "JANE", "VIRTU", "SUSG"]
    hft_size_threshold: 100
    institutional_size_threshold: 1000
    min_orders_required: 100
    toxicity_scores:
      toxic: 1.0
      hft: 0.7
      institutional: 0.2
      other: 0.3
  
  # New pattern-based toxicity detection
  toxicity_detection:
    method: "pattern_based"  # Switch from "market_maker_based" to this
    vpin_thresholds:
      toxic: 0.70
      informed: 0.30
    venue_scores:  # Venue-based toxicity scores (from Warning 2152)
      # Main exchanges (Depth venues)
      NASDAQ: 0.50   # NASDAQ main book (full name)
      NSDQ: 0.50     # NASDAQ main book (short code)
      NYSE: 0.35     # NYSE institutional
      ARCA: 0.40     # NYSE ARCA institutional
      BATS: 0.70     # CBOE BZX, mixed retail/HFT
      BEX: 0.65      # CBOE BEX, retail flow
      IEX: 0.20      # Speed bump protects from HFT
      
      # Secondary venues (Top venues from warning)
      BYX: 0.70      # CBOE BYX, retail-heavy
      PEARL: 0.75    # MIAX PEARL, options/retail
      AMEX: 0.45     # NYSE American, mixed flow
      MEMX: 0.65     # Members Exchange, aggressive pricing
      EDGEA: 0.75    # CBOE EDGA, retail flow
      EDGX: 0.80     # CBOE EDGX, retail-heavy PFOF
      DRCTEDGE: 0.75 # Direct Edge, retail
      PSX: 0.65      # NASDAQ PSX, retail-focused
      ISE: 0.70      # International Securities Exchange
      CHX: 0.60      # Chicago Stock Exchange
      LTSE: 0.40     # Long-Term Stock Exchange
      NYSENAT: 0.35  # NYSE National, institutional
      
      # IB internal and special venues
      IBEOS: 0.60    # IB's internal smart router
      IBKRATS: 0.60  # IB internal routing
      OVERNIGHT: 0.50 # Extended hours trading
      SMART: 0.50     # IB SMART routing (mixed flow)
      
      # Dark pools and unknown
      DARK: 0.50     # Unknown dark pool
      UNKNOWN: 0.50  # Default for unknown venues
    trade_patterns:
      odd_lot_weight: 0.70   # Odd lots indicate retail
      sweep_weight: 0.90     # Sweeps indicate aggressive/toxic
      block_weight: -0.50    # Large blocks indicate institutional
    block_threshold: 10000   # Shares for block trade
    sweep_window_ms: 250     # Time window for sweep detection
  
  volatility:
    window_bars: 20
    low_percentile: 33
    high_percentile: 67
    bars_per_day: 4680
    trading_days_per_year: 252
    min_bars_for_regime: 500
    default_regime: "NORMAL"
  
  correlation:
    min_bars: 100
    calculation_window: 500
    forward_fill_limit: 5
    min_correlation_symbols: 3

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/alphatrader.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5
  console: true
  colorize: true

# Monitoring configuration
monitoring:
  health_check_interval: 1
  heartbeat_timeout: 10
  alert_email: null