# AlphaTrader Pro Configuration
# Based on complete_tech_spec.md Section 12

# Redis Configuration
redis:
  host: localhost
  port: 6379
  decode_responses: true

# IBKR Configuration
ibkr:
  host: 127.0.0.1
  port: 7497  # Paper trading port
  client_id: 1
  account: DU1234567  # Replace with your paper account

# Alpha Vantage Configuration
alpha_vantage:
  api_key: YOUR_API_KEY_HERE
  calls_per_minute: 600

# Trading Configuration
trading:
  max_positions: 5
  max_per_symbol: 2
  daily_loss_limit: 2000
  max_consecutive_losses: 3
  symbols:
    - SPY
    - QQQ
    - IWM
    - AAPL
    - TSLA
    - NVDA
    - AMD
    - GOOGL
    - META
    - AMZN
    - MSFT
    - VXX

# Risk Management
risk:
  kelly_fraction: 0.25
  max_drawdown: 0.10
  var_limit: 2000

# Strategy Time Windows
strategies:
  zero_dte:
    start_time: "09:45"
    end_time: "15:00"
  one_dte:
    start_time: "14:00"
    end_time: "15:30"
  fourteen_dte:
    start_time: "09:30"
    end_time: "16:00"
  moc:
    start_time: "15:30"
    end_time: "15:50"

# Distribution
distribution:
  discord:
    basic_webhook: YOUR_WEBHOOK_URL
    premium_webhook: YOUR_WEBHOOK_URL

# Dashboard
dashboard:
  host: 0.0.0.0
  port: 8000

# Twitter Configuration
twitter:
  bearer_token: YOUR_BEARER_TOKEN
  consumer_key: YOUR_CONSUMER_KEY
  consumer_secret: YOUR_CONSUMER_SECRET
  access_token: YOUR_ACCESS_TOKEN
  access_token_secret: YOUR_ACCESS_TOKEN_SECRET

# Telegram Configuration
telegram:
  bot_token: YOUR_TELEGRAM_BOT_TOKEN
  channels:
    public: "@alphatrader_public"
    basic: "@alphatrader_basic"
    premium: "@alphatrader_premium"

# OpenAI Configuration
openai:
  api_key: YOUR_OPENAI_API_KEY

# Stripe Configuration
stripe:
  api_key: YOUR_STRIPE_API_KEY

# Scheduled Tasks
scheduled_tasks:
  morning_analysis: "08:00"
  market_open: "09:30"
  midday_update: "12:00"
  market_close: "16:00"
  evening_wrapup: "18:00"