generated_at: '2025-09-16T10:32:42.189368'
parameters:
  vpin_bucket_size: 200
  lookback_bars: 10
  flow_toxicity:
    SPY:
      toxicity: 0.505
      vpin: 0.5
      venue_tox: 0.5
      pattern_tox: 0.527
      book_tox: 0.5
      venue_mix:
        UNKNOWN: 1000
      label: neutral
    QQQ:
      toxicity: 0.503
      vpin: 0.5
      venue_tox: 0.5
      pattern_tox: 0.515
      book_tox: 0.5
      venue_mix:
        UNKNOWN: 1000
      label: neutral
    IWM:
      toxicity: 0.483
      vpin: 0.5
      venue_tox: 0.5
      pattern_tox: 0.417
      book_tox: 0.5
      venue_mix:
        UNKNOWN: 1000
      label: neutral
  vol_regimes:
    current: NORMAL
    error: No bar data
  correlation_matrix: {}
metadata:
  symbols_analyzed:
  - VXX
  - GOOGL
  - MSFT
  - AAPL
  - IWM
  - TSLA
  - NVDA
  - AMD
  - QQQ
  - AMZN
  - SPY
  - META
  discovery_config:
    enabled: true
    run_on_startup: true
    startup_delay: 60
    interval_seconds: 900
    schedule: 0 9 * * *
    ttl_seconds: 86400
    data_staleness_threshold: 3600
    vpin:
      min_bucket_size: 50
      max_bucket_size: 500
      num_clusters: 5
      min_trades_required: 1000
      default_bucket_size: 100
    temporal:
      max_lookback: 30
      min_bars_required: 100
      significance_threshold: 0.05
      default_lookback: 10
    market_makers:
      toxic_list:
      - CDRG
      - JANE
      - VIRTU
      - SUSG
      hft_size_threshold: 100
      institutional_size_threshold: 1000
      min_orders_required: 100
      toxicity_scores:
        toxic: 1.0
        hft: 0.7
        institutional: 0.2
        other: 0.3
    toxicity_detection:
      method: pattern_based
      vpin_thresholds:
        toxic: 0.7
        informed: 0.3
      venue_scores:
        NASDAQ: 0.5
        NSDQ: 0.5
        NYSE: 0.35
        ARCA: 0.4
        BATS: 0.7
        BEX: 0.65
        IEX: 0.2
        BYX: 0.7
        PEARL: 0.75
        AMEX: 0.45
        MEMX: 0.65
        EDGEA: 0.75
        EDGX: 0.8
        DRCTEDGE: 0.75
        PSX: 0.65
        ISE: 0.7
        CHX: 0.6
        LTSE: 0.4
        NYSENAT: 0.35
        IBEOS: 0.6
        IBKRATS: 0.6
        OVERNIGHT: 0.5
        SMART: 0.5
        DARK: 0.5
        UNKNOWN: 0.5
      trade_patterns:
        odd_lot_weight: 0.7
        sweep_weight: 0.9
        block_weight: -0.5
      block_threshold: 10000
      sweep_window_ms: 250
    volatility:
      window_bars: 20
      low_percentile: 33
      high_percentile: 67
      bars_per_day: 4680
      trading_days_per_year: 252
      min_bars_for_regime: 500
      default_regime: NORMAL
    correlation:
      min_bars: 100
      calculation_window: 500
      forward_fill_limit: 5
      min_correlation_symbols: 3
