option:
  initial_risk_pct: 0.45
  min_tick: 0.05
  min_improvement_pct: 0.05
  stages:
  - profit_pct: 0.0
    stop_type: TRAIL_PERCENT
    stop_value: 50.0
  - profit_pct: 2.5
    stop_type: TRAIL_PERCENT
    stop_value: 47.5
  - profit_pct: 5.0
    stop_type: TRAIL_PERCENT
    stop_value: 45.0
  - profit_pct: 7.5
    stop_type: TRAIL_PERCENT
    stop_value: 42.5
  - profit_pct: 10.0
    stop_type: TRAIL_PERCENT
    stop_value: 40.0
  - profit_pct: 12.5
    stop_type: TRAIL_PERCENT
    stop_value: 37.5
  - profit_pct: 15.0
    stop_type: TRAIL_PERCENT
    stop_value: 35.0
  - profit_pct: 17.5
    stop_type: TRAIL_PERCENT
    stop_value: 32.5
  - profit_pct: 20.0
    stop_type: TRAIL_PERCENT
    stop_value: 30.0
  - profit_pct: 22.5
    stop_type: TRAIL_PERCENT
    stop_value: 27.5
  - profit_pct: 25.0
    stop_type: TRAIL_PERCENT
    stop_value: 25.0
  - profit_pct: 27.5
    stop_type: TRAIL_PERCENT
    stop_value: 22.5
  - profit_pct: 30.0
    stop_type: TRAIL_PERCENT
    stop_value: 20.0
  - profit_pct: 32.5
    stop_type: TRAIL_PERCENT
    stop_value: 19.0
  - profit_pct: 35.0
    stop_type: TRAIL_PERCENT
    stop_value: 18.0
  - profit_pct: 37.5
    stop_type: TRAIL_PERCENT
    stop_value: 17.0
  - profit_pct: 40.0
    stop_type: TRAIL_PERCENT
    stop_value: 16.0
  - profit_pct: 42.5
    stop_type: TRAIL_PERCENT
    stop_value: 15.0
  - profit_pct: 45.0
    stop_type: TRAIL_PERCENT
    stop_value: 14.0
  - profit_pct: 47.5
    stop_type: TRAIL_PERCENT
    stop_value: 13.0
  - profit_pct: 50.0
    stop_type: TRAIL_PERCENT
    stop_value: 12.0
  - profit_pct: 52.5
    stop_type: TRAIL_PERCENT
    stop_value: 11.75
  - profit_pct: 55.0
    stop_type: TRAIL_PERCENT
    stop_value: 11.5
  - profit_pct: 57.5
    stop_type: TRAIL_PERCENT
    stop_value: 11.25
  - profit_pct: 60.0
    stop_type: TRAIL_PERCENT
    stop_value: 11.0
  - profit_pct: 62.5
    stop_type: TRAIL_PERCENT
    stop_value: 10.75
  - profit_pct: 65.0
    stop_type: TRAIL_PERCENT
    stop_value: 10.5
  - profit_pct: 67.5
    stop_type: TRAIL_PERCENT
    stop_value: 10.25
  - profit_pct: 70.0
    stop_type: TRAIL_PERCENT
    stop_value: 10.0
  - profit_pct: 72.5
    stop_type: TRAIL_PERCENT
    stop_value: 9.8
  - profit_pct: 75.0
    stop_type: TRAIL_PERCENT
    stop_value: 9.5
  - profit_pct: 77.5
    stop_type: TRAIL_PERCENT
    stop_value: 9.3
  - profit_pct: 80.0
    stop_type: TRAIL_PERCENT
    stop_value: 9.0
  - profit_pct: 82.5
    stop_type: TRAIL_PERCENT
    stop_value: 8.8
  - profit_pct: 85.0
    stop_type: FIXED_PERCENT
    stop_value: 8.5
  - profit_pct: 87.5
    stop_type: FIXED_PERCENT
    stop_value: 8.25
  - profit_pct: 90.0
    stop_type: FIXED_PERCENT
    stop_value: 8.0
  - profit_pct: 92.5
    stop_type: FIXED_PERCENT
    stop_value: 7.75
  - profit_pct: 95.0
    stop_type: FIXED_PERCENT
    stop_value: 7.5
  - profit_pct: 97.5
    stop_type: FIXED_PERCENT
    stop_value: 7.25
  - profit_pct: 100.0
    stop_type: FIXED_PERCENT
    stop_value: 7.0
  - profit_pct: 102.5
    stop_type: FIXED_PERCENT
    stop_value: 6.9
  - profit_pct: 105.0
    stop_type: FIXED_PERCENT
    stop_value: 6.8
  - profit_pct: 107.5
    stop_type: FIXED_PERCENT
    stop_value: 6.7
  - profit_pct: 110.0
    stop_type: FIXED_PERCENT
    stop_value: 6.6
  - profit_pct: 112.5
    stop_type: FIXED_PERCENT
    stop_value: 6.5
  - profit_pct: 115.0
    stop_type: FIXED_PERCENT
    stop_value: 6.4
  - profit_pct: 117.5
    stop_type: FIXED_PERCENT
    stop_value: 6.3
  - profit_pct: 120.0
    stop_type: FIXED_PERCENT
    stop_value: 6.2
  - profit_pct: 122.5
    stop_type: FIXED_PERCENT
    stop_value: 6.1
  - profit_pct: 125.0
    stop_type: FIXED_PERCENT
    stop_value: 6.0
  - profit_pct: 127.5
    stop_type: FIXED_PERCENT
    stop_value: 5.9
  - profit_pct: 130.0
    stop_type: FIXED_PERCENT
    stop_value: 5.8
  - profit_pct: 132.5
    stop_type: FIXED_PERCENT
    stop_value: 5.7
  - profit_pct: 135.0
    stop_type: FIXED_PERCENT
    stop_value: 5.6
  - profit_pct: 137.5
    stop_type: FIXED_PERCENT
    stop_value: 5.5
  - profit_pct: 140.0
    stop_type: FIXED_PERCENT
    stop_value: 5.4
  - profit_pct: 142.5
    stop_type: FIXED_PERCENT
    stop_value: 5.3
  - profit_pct: 145.0
    stop_type: FIXED_PERCENT
    stop_value: 5.2
  - profit_pct: 147.5
    stop_type: FIXED_PERCENT
    stop_value: 5.1
  - profit_pct: 150.0
    stop_type: FIXED_PERCENT
    stop_value: 5.0
  - profit_pct: 152.5
    stop_type: FIXED_PERCENT
    stop_value: 4.95
  - profit_pct: 155.0
    stop_type: FIXED_PERCENT
    stop_value: 4.9
  - profit_pct: 157.5
    stop_type: FIXED_PERCENT
    stop_value: 4.85
  - profit_pct: 160.0
    stop_type: FIXED_PERCENT
    stop_value: 4.8
  - profit_pct: 162.5
    stop_type: FIXED_PERCENT
    stop_value: 4.75
  - profit_pct: 165.0
    stop_type: FIXED_PERCENT
    stop_value: 4.7
  - profit_pct: 167.5
    stop_type: FIXED_PERCENT
    stop_value: 4.65
  - profit_pct: 170.0
    stop_type: FIXED_PERCENT
    stop_value: 4.6
  - profit_pct: 172.5
    stop_type: FIXED_PERCENT
    stop_value: 4.55
  - profit_pct: 175.0
    stop_type: FIXED_PERCENT
    stop_value: 4.5
  - profit_pct: 177.5
    stop_type: FIXED_PERCENT
    stop_value: 4.45
  - profit_pct: 180.0
    stop_type: FIXED_PERCENT
    stop_value: 4.4
  - profit_pct: 182.5
    stop_type: FIXED_PERCENT
    stop_value: 4.35
  - profit_pct: 185.0
    stop_type: FIXED_PERCENT
    stop_value: 4.3
  - profit_pct: 187.5
    stop_type: FIXED_PERCENT
    stop_value: 4.25
  - profit_pct: 190.0
    stop_type: FIXED_PERCENT
    stop_value: 4.2
  - profit_pct: 192.5
    stop_type: FIXED_PERCENT
    stop_value: 4.15
  - profit_pct: 195.0
    stop_type: FIXED_PERCENT
    stop_value: 4.1
  - profit_pct: 197.5
    stop_type: FIXED_PERCENT
    stop_value: 4.05
  - profit_pct: 200.0
    stop_type: FIXED_PERCENT
    stop_value: 4.0
  - profit_pct: 202.5
    stop_type: FIXED_PERCENT
    stop_value: 3.95
  - profit_pct: 205.0
    stop_type: FIXED_PERCENT
    stop_value: 3.9
  - profit_pct: 207.5
    stop_type: FIXED_PERCENT
    stop_value: 3.85
  - profit_pct: 210.0
    stop_type: FIXED_PERCENT
    stop_value: 3.8
  - profit_pct: 212.5
    stop_type: FIXED_PERCENT
    stop_value: 3.75
  - profit_pct: 215.0
    stop_type: FIXED_PERCENT
    stop_value: 3.7
  - profit_pct: 217.5
    stop_type: FIXED_PERCENT
    stop_value: 3.65
  - profit_pct: 220.0
    stop_type: FIXED_PERCENT
    stop_value: 3.6
  - profit_pct: 222.5
    stop_type: FIXED_PERCENT
    stop_value: 3.55
  - profit_pct: 225.0
    stop_type: FIXED_PERCENT
    stop_value: 3.5
  - profit_pct: 227.5
    stop_type: FIXED_PERCENT
    stop_value: 3.45
  - profit_pct: 230.0
    stop_type: FIXED_PERCENT
    stop_value: 3.4
  - profit_pct: 232.5
    stop_type: FIXED_PERCENT
    stop_value: 3.35
  - profit_pct: 235.0
    stop_type: FIXED_PERCENT
    stop_value: 3.3
  - profit_pct: 237.5
    stop_type: FIXED_PERCENT
    stop_value: 3.25
  - profit_pct: 240.0
    stop_type: FIXED_PERCENT
    stop_value: 3.2
  - profit_pct: 242.5
    stop_type: FIXED_PERCENT
    stop_value: 3.15
  - profit_pct: 245.0
    stop_type: FIXED_PERCENT
    stop_value: 3.1
  - profit_pct: 247.5
    stop_type: FIXED_PERCENT
    stop_value: 3.05
  - profit_pct: 250.0
    stop_type: FIXED_PERCENT
    stop_value: 3.0
  - profit_pct: 252.5
    stop_type: FIXED_PERCENT
    stop_value: 2.95
  - profit_pct: 255.0
    stop_type: FIXED_PERCENT
    stop_value: 2.9
  - profit_pct: 257.5
    stop_type: FIXED_PERCENT
    stop_value: 2.85
  - profit_pct: 260.0
    stop_type: FIXED_PERCENT
    stop_value: 2.8
  - profit_pct: 262.5
    stop_type: FIXED_PERCENT
    stop_value: 2.75
  - profit_pct: 265.0
    stop_type: FIXED_PERCENT
    stop_value: 2.7
  - profit_pct: 267.5
    stop_type: FIXED_PERCENT
    stop_value: 2.65
  - profit_pct: 270.0
    stop_type: FIXED_PERCENT
    stop_value: 2.6
  - profit_pct: 272.5
    stop_type: FIXED_PERCENT
    stop_value: 2.55
  - profit_pct: 275.0
    stop_type: FIXED_PERCENT
    stop_value: 2.5
  - profit_pct: 277.5
    stop_type: FIXED_PERCENT
    stop_value: 2.45
  - profit_pct: 280.0
    stop_type: FIXED_PERCENT
    stop_value: 2.4
  - profit_pct: 282.5
    stop_type: FIXED_PERCENT
    stop_value: 2.35
  - profit_pct: 285.0
    stop_type: FIXED_PERCENT
    stop_value: 2.3
  - profit_pct: 287.5
    stop_type: FIXED_PERCENT
    stop_value: 2.25
  - profit_pct: 290.0
    stop_type: FIXED_PERCENT
    stop_value: 2.2
  - profit_pct: 292.5
    stop_type: FIXED_PERCENT
    stop_value: 2.15
  - profit_pct: 295.0
    stop_type: FIXED_PERCENT
    stop_value: 2.1
  - profit_pct: 297.5
    stop_type: FIXED_PERCENT
    stop_value: 2.05
  - profit_pct: 300.0
    stop_type: FIXED_PERCENT
    stop_value: 2.0
  - profit_pct: 302.5
    stop_type: FIXED_PERCENT
    stop_value: 1.95
  - profit_pct: 305.0
    stop_type: FIXED_PERCENT
    stop_value: 1.9
  - profit_pct: 307.5
    stop_type: FIXED_PERCENT
    stop_value: 1.85
  - profit_pct: 310.0
    stop_type: FIXED_PERCENT
    stop_value: 1.8
  - profit_pct: 312.5
    stop_type: FIXED_PERCENT
    stop_value: 1.75
  - profit_pct: 315.0
    stop_type: FIXED_PERCENT
    stop_value: 1.7
  - profit_pct: 317.5
    stop_type: FIXED_PERCENT
    stop_value: 1.65
  - profit_pct: 320.0
    stop_type: FIXED_PERCENT
    stop_value: 1.6
  - profit_pct: 322.5
    stop_type: FIXED_PERCENT
    stop_value: 1.55
  - profit_pct: 325.0
    stop_type: FIXED_PERCENT
    stop_value: 1.5
  - profit_pct: 327.5
    stop_type: FIXED_PERCENT
    stop_value: 1.45
  - profit_pct: 330.0
    stop_type: FIXED_PERCENT
    stop_value: 1.4
  - profit_pct: 332.5
    stop_type: FIXED_PERCENT
    stop_value: 1.35
  - profit_pct: 335.0
    stop_type: FIXED_PERCENT
    stop_value: 1.3
  - profit_pct: 337.5
    stop_type: FIXED_PERCENT
    stop_value: 1.25
  - profit_pct: 340.0
    stop_type: FIXED_PERCENT
    stop_value: 1.2
  - profit_pct: 342.5
    stop_type: FIXED_PERCENT
    stop_value: 1.15
  - profit_pct: 345.0
    stop_type: FIXED_PERCENT
    stop_value: 1.1
  - profit_pct: 347.5
    stop_type: FIXED_PERCENT
    stop_value: 1.05
  - profit_pct: 350.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 352.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 355.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 357.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 360.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 362.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 365.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 367.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 370.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 372.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 375.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 377.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 380.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 382.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 385.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 387.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 390.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 392.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 395.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 397.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 400.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 402.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 405.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 407.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 410.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 412.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 415.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 417.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 420.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 422.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 425.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 427.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 430.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 432.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 435.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 437.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 440.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 442.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 445.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 447.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 450.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 452.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 455.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 457.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 460.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 462.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 465.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 467.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 470.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 472.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 475.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 477.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 480.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 482.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 485.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 487.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 490.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 492.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 495.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 497.5
    stop_type: FIXED_PERCENT
    stop_value: 1.0
  - profit_pct: 500.0
    stop_type: FIXED_PERCENT
    stop_value: 1.0
stock:
  initial_risk_pct: 0.04
  min_tick: 0.01
  min_improvement_pct: 0.01
  stages:
  - profit_pct: 0.0
    stop_type: TRAIL_PERCENT
    stop_value: 15.0
  - profit_pct: 5.0
    stop_type: TRAIL_PERCENT
    stop_value: 12.0
  - profit_pct: 10.0
    stop_type: TRAIL_PERCENT
    stop_value: 10.0
  - profit_pct: 15.0
    stop_type: TRAIL_PERCENT
    stop_value: 8.0
  - profit_pct: 20.0
    stop_type: TRAIL_PERCENT
    stop_value: 7.0
  - profit_pct: 25.0
    stop_type: TRAIL_PERCENT
    stop_value: 6.5
  - profit_pct: 30.0
    stop_type: TRAIL_PERCENT
    stop_value: 6.0
  - profit_pct: 35.0
    stop_type: TRAIL_PERCENT
    stop_value: 5.5
  - profit_pct: 40.0
    stop_type: FIXED_PERCENT
    stop_value: 5.0
  - profit_pct: 45.0
    stop_type: FIXED_PERCENT
    stop_value: 4.8
  - profit_pct: 50.0
    stop_type: FIXED_PERCENT
    stop_value: 4.5
  - profit_pct: 55.0
    stop_type: FIXED_PERCENT
    stop_value: 4.4
  - profit_pct: 60.0
    stop_type: FIXED_PERCENT
    stop_value: 4.3
  - profit_pct: 65.0
    stop_type: FIXED_PERCENT
    stop_value: 4.2
  - profit_pct: 70.0
    stop_type: FIXED_PERCENT
    stop_value: 4.1
  - profit_pct: 75.0
    stop_type: FIXED_PERCENT
    stop_value: 4.0
  - profit_pct: 80.0
    stop_type: FIXED_PERCENT
    stop_value: 3.9
  - profit_pct: 85.0
    stop_type: FIXED_PERCENT
    stop_value: 3.8
  - profit_pct: 90.0
    stop_type: FIXED_PERCENT
    stop_value: 3.7
  - profit_pct: 95.0
    stop_type: FIXED_PERCENT
    stop_value: 3.6
  - profit_pct: 100.0
    stop_type: FIXED_PERCENT
    stop_value: 3.5
  - profit_pct: 105.0
    stop_type: FIXED_PERCENT
    stop_value: 3.4
  - profit_pct: 110.0
    stop_type: FIXED_PERCENT
    stop_value: 3.3
  - profit_pct: 115.0
    stop_type: FIXED_PERCENT
    stop_value: 3.2
  - profit_pct: 120.0
    stop_type: FIXED_PERCENT
    stop_value: 3.1
  - profit_pct: 125.0
    stop_type: FIXED_PERCENT
    stop_value: 3.0
  - profit_pct: 130.0
    stop_type: FIXED_PERCENT
    stop_value: 2.9
  - profit_pct: 135.0
    stop_type: FIXED_PERCENT
    stop_value: 2.8
  - profit_pct: 140.0
    stop_type: FIXED_PERCENT
    stop_value: 2.7
  - profit_pct: 145.0
    stop_type: FIXED_PERCENT
    stop_value: 2.6
  - profit_pct: 150.0
    stop_type: FIXED_PERCENT
    stop_value: 2.5
  - profit_pct: 155.0
    stop_type: FIXED_PERCENT
    stop_value: 2.4
  - profit_pct: 160.0
    stop_type: FIXED_PERCENT
    stop_value: 2.3
  - profit_pct: 165.0
    stop_type: FIXED_PERCENT
    stop_value: 2.2
  - profit_pct: 170.0
    stop_type: FIXED_PERCENT
    stop_value: 2.1
  - profit_pct: 175.0
    stop_type: FIXED_PERCENT
    stop_value: 2.0
  - profit_pct: 180.0
    stop_type: FIXED_PERCENT
    stop_value: 1.9
  - profit_pct: 185.0
    stop_type: FIXED_PERCENT
    stop_value: 1.8
  - profit_pct: 190.0
    stop_type: FIXED_PERCENT
    stop_value: 1.7
  - profit_pct: 195.0
    stop_type: FIXED_PERCENT
    stop_value: 1.6
  - profit_pct: 200.0
    stop_type: FIXED_PERCENT
    stop_value: 1.5
default:
  initial_risk_pct: 0.2
  min_tick: 0.02
  min_improvement_pct: 0.02
  stages:
  - profit_pct: 0.0
    stop_type: TRAIL_PERCENT
    stop_value: 20.0
  - profit_pct: 10.0
    stop_type: FIXED_PERCENT
    stop_value: 5.0
  - profit_pct: 20.0
    stop_type: FIXED_PERCENT
    stop_value: 3.5
  - profit_pct: 30.0
    stop_type: FIXED_PERCENT
    stop_value: 2.0
