-- Rollback for complete schema
-- WARNING: This will DROP all tables and data!

BEGIN;

DROP TABLE IF EXISTS willr CASCADE;
DROP TABLE IF EXISTS vwap CASCADE;
DROP TABLE IF EXISTS stoch CASCADE;
DROP TABLE IF EXISTS sma CASCADE;
DROP TABLE IF EXISTS rsi CASCADE;
DROP TABLE IF EXISTS obv CASCADE;
DROP TABLE IF EXISTS mom CASCADE;
DROP TABLE IF EXISTS mfi CASCADE;
DROP TABLE IF EXISTS macd CASCADE;
DROP TABLE IF EXISTS ema CASCADE;
DROP TABLE IF EXISTS cci CASCADE;
DROP TABLE IF EXISTS bbands CASCADE;
DROP TABLE IF EXISTS atr CASCADE;
DROP TABLE IF EXISTS aroon CASCADE;
DROP TABLE IF EXISTS adx CASCADE;
DROP TABLE IF EXISTS ad CASCADE;
DROP TABLE IF EXISTS top_gainers_losers CASCADE;
DROP TABLE IF EXISTS news_sentiment CASCADE;
DROP TABLE IF EXISTS insider_transactions CASCADE;
DROP TABLE IF EXISTS realtime_options CASCADE;
DROP TABLE IF EXISTS historical_options CASCADE;
DROP TABLE IF EXISTS splits CASCADE;
DROP TABLE IF EXISTS overview CASCADE;
DROP TABLE IF EXISTS income_statement CASCADE;
DROP TABLE IF EXISTS earnings CASCADE;
DROP TABLE IF EXISTS dividends CASCADE;
DROP TABLE IF EXISTS cash_flow CASCADE;
DROP TABLE IF EXISTS balance_sheet CASCADE;
DROP TABLE IF EXISTS treasury_yield CASCADE;
DROP TABLE IF EXISTS real_gdp CASCADE;
DROP TABLE IF EXISTS inflation CASCADE;
DROP TABLE IF EXISTS federal_funds_rate CASCADE;
DROP TABLE IF EXISTS cpi CASCADE;
DROP TABLE IF EXISTS analytics_sliding_window CASCADE;
DROP TABLE IF EXISTS analytics_fixed_window CASCADE;
DROP TABLE IF EXISTS field_mappings CASCADE;
DROP TABLE IF EXISTS data_transformations CASCADE;
DROP TABLE IF EXISTS api_response CASCADE;

COMMIT;
